import cardOrangeImg from "../../assets/cardOrangeImg.svg";
import cardStonesImg from "../../assets/cardStonesImg.svg";
import cardPinkImg from "../../assets/cardPinkImg.svg";
import cardGreyImg from "../../assets/cardGreyImg.svg";
import cardPlanetImg from "../../assets/cardPlanetImg.svg";
import idUser from "generate-unique-id";

export const discoverList = [
  {
    id: idUser(),
    img: cardOrangeImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardStonesImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardPinkImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardGreyImg,
    time: "19H 09m 12s",
    title: "NuEvey",
    subtitle: "Current bid",
    rating: "1.25",
  },
  {
    id: idUser(),
    img: cardPlanetImg,
    time: "19H 09m 12s",
    title: "NuEvey",
    subtitle: "Current bid",
    rating: "1.25",
  },
  {
    id: idUser(),
    img: cardGreyImg,
    time: "19H 09m 12s",
    title: "NuEvey",
    subtitle: "Current bid",
    rating: "1.25",
  },
  {
    id: idUser(),
    img: cardStonesImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardOrangeImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardOrangeImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardStonesImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardPinkImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardGreyImg,
    time: "19H 09m 12s",
    title: "NuEvey",
    subtitle: "Current bid",
    rating: "1.25",
  },
  {
    id: idUser(),
    img: cardPlanetImg,
    time: "19H 09m 12s",
    title: "NuEvey",
    subtitle: "Current bid",
    rating: "1.25",
  },
  {
    id: idUser(),
    img: cardGreyImg,
    time: "19H 09m 12s",
    title: "NuEvey",
    subtitle: "Current bid",
    rating: "1.25",
  },
  {
    id: idUser(),
    img: cardStonesImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
  {
    id: idUser(),
    img: cardOrangeImg,
    time: "07h 09m 12s",
    title: "Sun-Glass",
    subtitle: "Current bid",
    rating: "1.75",
  },
];
